### ISSUE TITLE
RegexProvider apparently causing "No compiled representation for provided namespace" error in .NET 6

### ISSUE THREAD

**Issue by geysernrd** [fable-compiler/Fable.RegexProvider#9]
Hi Team,

I tried upgrading a library from .NET 5 to .NET 6 today, and I got this obscure build error: "error FS0192 : internal error : No compiled representation for provided namespace".  After a bunch of trial-and-error, I found that eliminating my library's reference to Fable.RegexProvider (and commenting out all the uses of SafeRegex) caused the problem to go away. 

Just "open Fable.RegexProvider" is sufficient to cause the build error, even if I don't use it in my code otherwise.

Any idea what might be causing that, and whether it is fixable?

Thanks,
Nathan

**Comment by alfonsogarciacaro** [comment]
Hi Nathan! Thanks a lot for your report. This is strange, this seems to be an internal error from the F# compiler: https://github.com/fsharp/fsharp/blob/577d06b9ec7192a6adafefd09ade0ed10b13897d/src/fsharp/tast.fs#L1194

Apparently there've been some regressions in the F# compiler so this could be one of them. Which version of Fable are you using? (You can check it with `dotnet fable --version`) Anyways I will check, maybe it can be solved by recompiling Fable.RegexProvider for dotnet 6.

**Comment by geysernrd** [comment]
Hi Alfonso! My downstream SAFE Stack project is on Fable 3.2.1 at the moment, but the upgrade to this upstream class library is meant to be the beginning of upgrading everything. The class lib itself uses Fable.RegexProvider but nothing else from Fable.

Hopefully a .NET 6 rebuild of SafeRegex solves the issue. If it doesn't, do you happen to know of any other Regex provider that works reliably when transpiled by Fable (for canonicalization and validation when converting raw input strings to domain types)?

**Comment by alfonsogarciacaro** [comment]
Actually, the main reason to have a specific Regex Provider for Fable was because the "standard" [F# Regex Provider](http://fsprojects.github.io/FSharp.Text.RegexProvider/) used named groups and Fable didn't support them at the time. But it does support them now, so I wonder if we can just use FSharp.Text.RegexProvider directly now 🤔 I need to check.

**Comment by alfonsogarciacaro** [comment]
Ok, I had to adjust one thing, but with the 3.7.18 release, FSharp.Text.RegexProvider seems to work with Fable :tada: Can you please give it a try @geysernrd?

**Comment by geysernrd** [comment]
Awesome, will do! My upgrade path is a bit complicated (and one of several tasks I'm working on simultaneously), but I will let you know how it worked ASAP.

**Comment by geysernrd** [comment]
Sorry, since I'm here: Is there a simple command to upgrade the Fable compiler? I let the SAFE Stack template handle everything initially and haven't really revisited it till now. Thanks!

**Comment by alfonsogarciacaro** [comment]
Yes :) You can update it as any other dotnet tool, so typing `dotnet tool update fable` should do the trick 👍

**Comment by geysernrd** [comment]
Success! The overall upgrade was every bit the adventure I expected, but now that my app is running again, code written using FSharp.Text.RegexProvider is working correctly in Fable. Thanks so much, @alfonsogarciacaro!

**Comment by alfonsogarciacaro** [comment]
Thanks for confirming @geysernrd! We probably can deprecate/archive this repo now, as the main reason for its existence was Fable/JS didn't support Regex named groups at the time.

What problems did you have when upgrading Fable btw? We always try to avoid regressions but sometimes we made mistakes 😅
